/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CmJwpShowcase {}
}

declare global {


  interface HTMLCmJwpShowcaseElement extends Components.CmJwpShowcase, HTMLStencilElement {}
  var HTMLCmJwpShowcaseElement: {
    prototype: HTMLCmJwpShowcaseElement;
    new (): HTMLCmJwpShowcaseElement;
  };
  interface HTMLElementTagNameMap {
    'cm-jwp-showcase': HTMLCmJwpShowcaseElement;
  }
}

declare namespace LocalJSX {
  interface CmJwpShowcase {}

  interface IntrinsicElements {
    'cm-jwp-showcase': CmJwpShowcase;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'cm-jwp-showcase': LocalJSX.CmJwpShowcase & JSXBase.HTMLAttributes<HTMLCmJwpShowcaseElement>;
    }
  }
}


