/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CmJwpShowcase {}
  interface CmTournament {}
}

declare global {


  interface HTMLCmJwpShowcaseElement extends Components.CmJwpShowcase, HTMLStencilElement {}
  var HTMLCmJwpShowcaseElement: {
    prototype: HTMLCmJwpShowcaseElement;
    new (): HTMLCmJwpShowcaseElement;
  };

  interface HTMLCmTournamentElement extends Components.CmTournament, HTMLStencilElement {}
  var HTMLCmTournamentElement: {
    prototype: HTMLCmTournamentElement;
    new (): HTMLCmTournamentElement;
  };
  interface HTMLElementTagNameMap {
    'cm-jwp-showcase': HTMLCmJwpShowcaseElement;
    'cm-tournament': HTMLCmTournamentElement;
  }
}

declare namespace LocalJSX {
  interface CmJwpShowcase {}
  interface CmTournament {}

  interface IntrinsicElements {
    'cm-jwp-showcase': CmJwpShowcase;
    'cm-tournament': CmTournament;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'cm-jwp-showcase': LocalJSX.CmJwpShowcase & JSXBase.HTMLAttributes<HTMLCmJwpShowcaseElement>;
      'cm-tournament': LocalJSX.CmTournament & JSXBase.HTMLAttributes<HTMLCmTournamentElement>;
    }
  }
}


